# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodwatch', '0002_auto_20171207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perps',
            name='date_created',
            field=models.DateField(default=datetime.date(2017, 12, 18)),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateField(default=datetime.date(2017, 12, 18)),
        ),
    ]
