# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseType',
            fields=[
                ('abuse_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('abuse_type_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CallType',
            fields=[
                ('call_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_number', models.CharField(blank=True, default='0', max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('middle_init', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=12)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('address_1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('address_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date_of_first_contact', models.DateField(default=datetime.date.today)),
                ('emergency_contact_name', models.CharField(default=None, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(default=None, max_length=12, null=True)),
                ('secondary_victim', models.CharField(default=None, max_length=200, null=True)),
                ('abusetype', models.ManyToManyField(blank=True, to='clients.AbuseType')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=200)),
                ('avenues_support', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('demographics_id', models.AutoField(primary_key=True, serialize=False)),
                ('demographics_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('ethnicity_id', models.AutoField(primary_key=True, serialize=False)),
                ('ethnicity_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_abbreviation', models.CharField(max_length=2)),
                ('state_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_description', models.CharField(default=None, max_length=200)),
                ('date_created', models.DateField(default=datetime.date(2017, 12, 12))),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='clients.State'),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Type'),
        ),
        migrations.AddField(
            model_name='clients',
            name='county_of_incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_of_incident', to='clients.County'),
        ),
        migrations.AddField(
            model_name='clients',
            name='county_of_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='county_of_residence', to='clients.County'),
        ),
        migrations.AddField(
            model_name='clients',
            name='demographics',
            field=models.ManyToManyField(blank=True, to='clients.Demographics'),
        ),
        migrations.AddField(
            model_name='clients',
            name='ethnicity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Ethnicity'),
        ),
        migrations.AddField(
            model_name='clients',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Gender'),
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.State'),
        ),
        migrations.AddField(
            model_name='clients',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Status'),
        ),
    ]
