# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='secondary_victim',
            new_name='primary_victim',
        ),
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateField(default=datetime.date(2017, 12, 13)),
        ),
    ]
