# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20171213_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateField(default=datetime.date(2017, 12, 14)),
        ),
    ]
