# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodwatch', '0006_auto_20171220_0910'),
        ('clients', '0003_auto_20171214_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='perp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborhoodwatch.Perps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='perp_relationship',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_created',
            field=models.DateField(default=datetime.date(2017, 12, 20)),
        ),
    ]
