# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 16:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_auto_20171214_1059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('call_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_call', models.DateTimeField(default=datetime.datetime.now)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('middle_init', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('victims_name', models.CharField(default=None, max_length=200)),
                ('safe_phone_contact', models.CharField(default=None, max_length=12)),
                ('safe_call', models.BooleanField(default=0)),
                ('address_1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('address_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('abusers_name', models.CharField(default=None, max_length=200)),
                ('abusers_city', models.CharField(default=None, max_length=200)),
                ('immediate_danger', models.BooleanField(default=0)),
                ('previous_victim_dv', models.BooleanField(default=0)),
                ('dv_when', models.DateField(default=None)),
                ('previous_victim_sa', models.BooleanField(default=0)),
                ('sa_when', models.DateField(default=None)),
                ('children', models.BooleanField(default=0)),
                ('num_children', models.IntegerField(max_length=3)),
                ('hear_about_avenues', models.CharField(default=None, max_length=200, null=True)),
                ('callback', models.BooleanField(default=0)),
                ('call_length', models.IntegerField(default=None, max_length=3)),
                ('nature_of_problem', models.CharField(default=None, max_length=200, null=True)),
                ('previous_client', models.BooleanField(default=0)),
                ('pc_when', models.DateField(default=None)),
                ('by_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_back', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallLogType',
            fields=[
                ('call_log_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_log_type_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_log_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calllog.CallLogType'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='county_of_incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_log_county_of_incident', to='clients.County'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='county_of_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_log_county_of_residence', to='clients.County'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.State'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='taken_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_taken_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
