# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20171214_1059'),
        ('calllog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_age', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='calllog',
            name='call_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
        migrations.AddField(
            model_name='child',
            name='call_log_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calllog.CallLog'),
        ),
        migrations.AddField(
            model_name='child',
            name='child_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Gender'),
        ),
    ]
