# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calllog', '0002_auto_20171214_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='children_info',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
