# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_auto_20171220_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('aquired_date', models.CharField(max_length=15)),
                ('aquired_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BedSize',
            fields=[
                ('bedsize_id', models.AutoField(primary_key=True, serialize=False)),
                ('bedsize_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('floors_id', models.AutoField(primary_key=True, serialize=False)),
                ('floors_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_occupancy', models.CharField(max_length=3)),
                ('floor_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Floors')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('shelter_name', models.CharField(max_length=200)),
                ('shelter_address_1', models.CharField(max_length=200)),
                ('shelter_adddress_2', models.CharField(max_length=200)),
                ('shelter_city', models.CharField(max_length=200)),
                ('shelter_zip', models.CharField(max_length=10)),
                ('mailing_address_1', models.CharField(max_length=200)),
                ('mailing_adddress_2', models.CharField(max_length=200)),
                ('mailing_city', models.CharField(max_length=200)),
                ('mailing_zip', models.CharField(max_length=10)),
                ('date_opened', models.CharField(max_length=15)),
                ('date_closed', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('aquired_date', models.CharField(max_length=15)),
                ('aquired_by', models.CharField(max_length=200)),
                ('mailing_state', models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_state', to='clients.State')),
                ('shelter_state', models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='physical_state', to='clients.State')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Status'),
        ),
        migrations.AddField(
            model_name='room',
            name='shelter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.Shelter'),
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.BedSize'),
        ),
        migrations.AddField(
            model_name='bed',
            name='client_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_id',
            field=models.ManyToManyField(to='shelter.Room'),
        ),
    ]
