# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='aquired_by',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='aquired_date',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='aquired_by',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='aquired_date',
        ),
    ]
