# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20171221_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=101, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_location',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Floors',
        ),
    ]
