# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20171228_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='room_id',
        ),
        migrations.AddField(
            model_name='bed',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shelter.Room'),
            preserve_default=False,
        ),
    ]
