# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20171228_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='client_assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='shelter.Room'),
        ),
    ]
