# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_auto_20180102_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='client_assigned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients', unique=True),
        ),
    ]
