# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_auto_20180104_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
